# NumPy IO

In [1]:
import numpy as np
np.random.seed(983456)

## Reading and writing a single NumPy array

In [2]:
arr = np.random.randint(10, size=(5,6))

In [3]:
np.save('int_array', arr) #This is the default and simplest way to save an array. It doesn't just save the data, but also the structure.

In [4]:
arr_read = np.load('int_array.npy') #This reads the file back

Mostly, np.save and np.load are the functions that one would use. The rest are good to know still, but these are the most used.

In [5]:
arr_read

array([[4, 4, 8, 1, 4, 0],
       [5, 5, 4, 4, 1, 6],
       [6, 3, 1, 1, 8, 8],
       [7, 9, 3, 3, 6, 5],
       [7, 6, 7, 5, 8, 1]])

In [6]:
arr # We see that arr and the loaded arr are the same

array([[4, 4, 8, 1, 4, 0],
       [5, 5, 4, 4, 1, 6],
       [6, 3, 1, 1, 8, 8],
       [7, 9, 3, 3, 6, 5],
       [7, 6, 7, 5, 8, 1]])

## Reading and writing multiple NumPy arrays

In [7]:
float_arr = np.random.randn(123,17)

In [9]:
np.savez('multiple_arrays', arr, float_arr) #This saves multiple arrays, uncompressed. arrays are provided as arguements


In [10]:
arrays = np.load('multiple_arrays.npz') #reading it back is different than before. We can see by running the next cell...
#If we go to the actual file, we see that its a folder containing two files, as we can see from the next cell.

In [11]:
arrays.files

['arr_0', 'arr_1']

In [12]:
arrays['arr_0'] # We have to select which array we would like to select from our archive

array([[4, 4, 8, 1, 4, 0],
       [5, 5, 4, 4, 1, 6],
       [6, 3, 1, 1, 8, 8],
       [7, 9, 3, 3, 6, 5],
       [7, 6, 7, 5, 8, 1]])

In [13]:
np.savez('multiple_arrays', int_array=arr, float_arr=float_arr)
#If we wanted to, we could provide our own names for each array, as this cell does

In [14]:
arrays = np.load('multiple_arrays.npz')

In [15]:
arrays.files

['int_array', 'float_arr']

In [16]:
float_arr_read = arrays['float_arr']

In [17]:
float_arr_read

array([[ 0.14924434, -2.08493571,  0.11729357, ..., -0.54995548,
        -0.59040315,  0.47577715],
       [ 1.70623984, -0.67554413,  1.61767403, ...,  0.79989211,
        -0.01350567,  0.92686051],
       [ 0.27182938,  0.71690637, -1.79837786, ...,  0.71665428,
         1.94437093, -1.25696469],
       ...,
       [ 0.43230419,  1.70339762, -0.46421423, ..., -0.7107336 ,
        -0.93582927, -0.34782732],
       [-1.23050782,  0.17687026, -1.06103308, ...,  0.205937  ,
        -1.18322041,  0.70596459],
       [-0.05555481, -0.0736679 , -0.2608711 , ...,  0.20774802,
        -1.12778734,  1.52588828]])

In [18]:
float_arr

array([[ 0.14924434, -2.08493571,  0.11729357, ..., -0.54995548,
        -0.59040315,  0.47577715],
       [ 1.70623984, -0.67554413,  1.61767403, ...,  0.79989211,
        -0.01350567,  0.92686051],
       [ 0.27182938,  0.71690637, -1.79837786, ...,  0.71665428,
         1.94437093, -1.25696469],
       ...,
       [ 0.43230419,  1.70339762, -0.46421423, ..., -0.7107336 ,
        -0.93582927, -0.34782732],
       [-1.23050782,  0.17687026, -1.06103308, ...,  0.205937  ,
        -1.18322041,  0.70596459],
       [-0.05555481, -0.0736679 , -0.2608711 , ...,  0.20774802,
        -1.12778734,  1.52588828]])

## Reading and writing text files

In [19]:
from io import StringIO

In [20]:
np.loadtxt(StringIO("1 2\n3 4"))

array([[1., 2.],
       [3., 4.]])

In [21]:
np.loadtxt(StringIO("a b\n1 2\n3 4"), skiprows=1)

array([[1., 2.],
       [3., 4.]])

In [22]:
np.loadtxt(StringIO("a,b\n1,2\n3,4"), skiprows=1) #This one fails, because the default delimeter for this is space, we have to explicate the delimeter ourselves (below)

ValueError: could not convert string to float: '1,2'

In [23]:
np.loadtxt(StringIO("a,b\n1,2\n3,4"), skiprows=1, delimiter=',')

array([[1., 2.],
       [3., 4.]])

In [24]:
np.savetxt('arr_text.csv', arr, delimiter=',', header="Fancy,header", comments='')
#If we open this file, we will see it have a header with five rows, multiple elements each.
#However, it is quite inefficient to store data like this, as it stores it like a float. So usually its better to store them as numpy arrays.

In [ ]:
?np.savetxt #Opening this shows us all of the other aspects we are able to change.

In [ ]:
arr

In [ ]:
?np.genfromtxt