# Linear algebra

In [1]:
import numpy as np

In [2]:
v = np.random.randint(10, size=(3,))
m = np.random.randint(10, size=(5, 3))

In [3]:
m

array([[1, 6, 9],
       [9, 5, 2],
       [9, 4, 6],
       [8, 0, 7],
       [0, 4, 2]])

In [4]:
v

array([3, 6, 4])

## Dot products, determinants, traces

Dot product is available through `np` itself (as it's very common). Note the ordering and dimensions:

In [5]:
np.dot(m, v)
#Even though the unit dimensions don't match, numpy transforms for the right dimensions for us so that it works.

array([75, 65, 75, 52, 32])

In [6]:
np.dot(m, v[:, np.newaxis]) #np.newaxis adds a new dimension

array([[75],
       [65],
       [75],
       [52],
       [32]])

In [8]:
m.T

array([[1, 9, 9, 8, 0],
       [6, 5, 4, 0, 4],
       [9, 2, 6, 7, 2]])

In [9]:
np.dot(v, m.T)
#This one is mathematically correct, as m  has been transformed and is now the right dimensions

array([75, 65, 75, 52, 32])

Inverse matrix is straighforward (as almost any other LA operation):

In [10]:
s = np.random.randint(10, size=(3,3))
s_inv = np.linalg.inv(s)

In [11]:
s

array([[5, 7, 2],
       [8, 5, 8],
       [2, 1, 3]])

In [12]:
s_inv

array([[-0.28,  0.76, -1.84],
       [ 0.32, -0.44,  0.96],
       [ 0.08, -0.36,  1.24]])

In [14]:
s_inv.dtype
#We see that our dtpye changed in the inreverse matrix.

dtype('float64')

In [13]:
np.dot(s_inv, s)
#this gives us the identity matrix, it just looks weird because of the floating point data type.

array([[ 1.00000000e+00, -2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16, -2.22044605e-16,  1.00000000e+00]])

Determinants and traces are available as well:

In [15]:
np.linalg.det(s), np.linalg.det(s_inv)  # det(s) == 1 / det(s_inv), btw

(-24.999999999999996, -0.03999999999999999)

In [16]:
np.trace(s), np.trace(s_inv)
#Sums of the diagonal values

(13, 0.52)

## Eigenvalues, eigenvectors

Eigenvalue decomposition (and other decompositions as well) are available via `eig` and `eigh` functions:

In [17]:
evals, evectors = np.linalg.eig(s)
#Eigenvalues sum up to the trace of the original matrix

In [18]:
evals

array([-1.81024968, 13.81024968,  1.        ])

In [19]:
evectors

array([[-0.73009094,  0.6367793 , -0.74420841],
       [ 0.66294688,  0.74802461,  0.24806947],
       [ 0.16573672,  0.18700615,  0.62017367]])

In [20]:
np.allclose(evals.sum(), np.trace(s))  # some simple LA and correct way of comparing floating point numbers
#We don't compare these with the normal operator, because there is a miniscule difference between the two, 
#when dealing with floating point numbers

True

Creating a diagonal matrix from a `1D` array:

In [21]:
s_diagonal = np.diag(evals)

In [22]:
s_diagonal

array([[-1.81024968,  0.        ,  0.        ],
       [ 0.        , 13.81024968,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

And now our matrix can be decomposed as:
    
$$
s = VEV^{-1}
$$

where $E$ is a diagonal matrix (with eigenvalues on main diagonal), and $V$ is a matrix where columns are eigenvectors.

In [24]:
np.dot(evectors, np.dot(s_diagonal, np.linalg.inv(evectors)))
#Putting these all together gives us the original array

array([[5., 7., 2.],
       [8., 5., 8.],
       [2., 1., 3.]])

In [25]:
s

array([[5, 7, 2],
       [8, 5, 8],
       [2, 1, 3]])

In [26]:
np.allclose(np.dot(evectors, np.dot(s_diagonal, np.linalg.inv(evectors))), s)

True