In [ ]:
import numpy as np

In [ ]:
l = [f'{x}' for x in range(10**6)]
b = len([x for x in l if '53' in str(x)])/10**10
float(b)

In [ ]:
avg =np.mean(array, axis = 1)
std = np.std(array, axis = 1)
np.vstack[(avg, std]).T

In [ ]:
import numpy as np

In [ ]:
%pylab inline

In [ ]:
arr1 = np.random.randn(100)
arr2 = np.random.randn(100)

In [ ]:
plt.figure()
plt.plot(arr1, arr2)

In [ ]:
fig = plt.figure()
line_plot = plt.plot(arr1)

plt.title('title')
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.tight_layout()


In [ ]:
%pylab inline

In [ ]:
x = np.linspace(0, 4*np.pi, 1000)

y = np.sin(x) + np.random.normal(0, 0.1, 1000) #adding these normal numbers to each

In [ ]:
plt.figure()
plt.plot(x,y)

In [ ]:
plt.figure(figsize = (6,6))
plt.plot(x ,y, 'o', c = 'firebrick', markersize = 6, label = 'noisy')
plt.legend(loc = 0)

In [2]:
import numpy as np

In [5]:
n = 5
arr = np.random.normal(size = (3,4))
arr

np.add(arr, (-(np.mean(arr) / np.std(arr))))


array([[ 0.56812034,  0.62014627, -0.12319828,  0.90109123],
       [ 0.70114125, -1.58197694,  0.64481777, -0.65142536],
       [ 0.33545697,  0.23221198, -0.19374391, -1.04188983]])

In [7]:
arr

array([[ 0.75590272,  0.65265774,  0.22670184, -0.62144408],
       [ 0.56737708, -1.7157411 ,  0.51105361, -0.78518952],
       [ 0.2016928 ,  0.09844782, -0.32750807, -1.17565399]])

In [53]:
arr = np.random.normal(size = (6,3))

In [50]:
array = np.zeros((6,3))
for x in range(arr.shape[0]):
    array[x] = arr[x] - (np.mean(arr[x])/ np.std(arr[x]))
print(array)

[[-0.91300153  0.64338141 -0.10411076]
 [-0.38697912  0.89493744 -1.03090983]
 [-1.16525087  1.07421816  0.22658688]
 [-0.99954743  1.36661822 -0.36716735]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [99]:
arr = np.random.normal(size = (3,5))
axis = 1

In [100]:
def norm(arr, axis):
    mean = arr.mean(axis = axis)
    std = arr.std(axis = axis)
    if (mean/std).shape[0] == arr.shape[1]:
        return arr- mean/std
    else:
       return arr - np.expand_dims(mean/std, axis = axis)
norm(arr, axis)

array([[-0.27632114, -0.45404551, -1.19987488, -0.82973919, -0.57519412],
       [ 2.49806184, -3.32063483,  0.83210679,  0.17712791, -0.12998554],
       [ 0.15110685,  0.42025453,  0.06207719, -1.50731905,  0.21811853]])

In [89]:
print('arr :', arr)
print('norm',  mean/std)
print(arr.shape)
if (mean/std).shape[0] == arr.shape[1]:
    print('no change', arr- mean/std)
else:
    print('expanded', arr - np.expand_dims(mean/std, axis = axis))
    


arr : [[-1.60220419  0.80776887  0.97504854 -0.71103669 -0.82089682]
 [-0.0302185   0.03773567  1.10368127  0.41507281  0.24553008]
 [ 0.25985446 -0.13657808  1.41057576 -0.00425387  0.26998161]
 [-0.27567975  1.59763408 -1.09966659  0.40916798 -1.02532971]
 [ 0.04066404 -1.83360418  1.19069939 -1.4994716  -2.50881196]
 [-0.61411062 -1.58013567  0.31989792  0.62808726  1.27488622]
 [ 1.19459871  1.02089816  0.47707378 -0.50374834  0.04662552]
 [-0.0806043   1.51960658  1.41986428  2.52065617  0.24354646]
 [ 1.19913411 -0.39941712  3.07388453 -1.04645387 -0.2280377 ]
 [-0.06830884  0.5620006   0.77194952  0.83564675  0.58375247]
 [ 0.62965932  0.36514585  0.49886808  0.21802148 -0.51329592]
 [ 0.46426859  1.0605982  -0.20726488 -1.33575704 -2.20341172]]
norm [-0.27068394  0.872288    0.65687012 -0.07857553 -0.68453761  0.00572734
  0.71529488  1.19599755  0.35300483  1.67553307  0.59828553 -0.37456286]
(12, 5)
expanded [[-1.33152024  1.07845282  1.24573248 -0.44035274 -0.55021287]
 [-0.

In [80]:
arr - (mean/std)

array([[ 0.67934055, -0.30191574, -0.91849804, -0.57416436, -0.51612423],
       [ 0.79959267,  1.60544997, -1.35325055, -0.14188819, -0.78052554],
       [ 1.25321396, -1.31094582,  1.73248681,  1.03007389,  0.80532363]])

In [135]:
arr_1d = np.random.randint(10, size = (3,5))
arr_2d = np.random.randint(10, size = (5))
arr_1d, arr_2d, np.dot(arr_1d, arr_2d)



(array([[3, 0, 5, 1, 8],
        [1, 5, 5, 5, 1],
        [4, 1, 7, 6, 9]]),
 array([3, 5, 5, 4, 1]),
 array([46, 74, 85]))

In [136]:
np.sum(arr_1d * arr_2d, axis = 1)

array([46, 74, 85])